name: Build Sactorium

on:
  push:
    branches: [ main, windows-build ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ main ]
  workflow_dispatch: # Permite execução manual

jobs:
  build-windows:
    runs-on: windows-latest
    if: contains(github.ref, 'windows-build') || startsWith(github.ref, 'refs/tags/v') || github.event_name == 'workflow_dispatch'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Build Windows
      run: npm run dist:win
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Upload Windows Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: sactorium-windows
        path: |
          dist/windows/*.exe
          dist/windows/*.exe.blockmap
          dist/windows/latest.yml
        retention-days: 30

  build-mac:
    runs-on: macos-latest
    if: contains(github.ref, 'main') || startsWith(github.ref, 'refs/tags/v') || github.event_name == 'workflow_dispatch'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Build macOS
      run: npm run dist
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Upload macOS Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: sactorium-mac
        path: |
          dist/*.dmg
          dist/*.dmg.blockmap
          dist/latest-mac.yml
        retention-days: 30

  release:
    needs: [build-windows, build-mac]
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v') && github.event_name == 'push'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Download Windows Artifacts
      uses: actions/download-artifact@v4
      with:
        name: sactorium-windows
        path: ./windows-build/
        
    - name: Download macOS Artifacts  
      uses: actions/download-artifact@v4
      with:
        name: sactorium-mac
        path: ./mac-build/
        
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          ./windows-build/*
          ./mac-build/*
        generate_release_notes: true
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}